-- SLW Travel · Supabase schema
-- Run this in: Supabase Dashboard → SQL Editor → New query

-- ── Trips ────────────────────────────────────────────────────────────
create table if not exists public.trips (
  id          uuid        primary key,          -- generated by crypto.randomUUID() on client
  user_id     uuid        not null references auth.users(id) on delete cascade,
  title       text        not null default '',
  data        jsonb       not null default '{}', -- full trip blob (stops, legs, notes, budget, currency)
  updated_at  timestamptz not null default now()
);

-- Index for fast per-user queries
create index if not exists trips_user_id_idx on public.trips(user_id);

-- Row Level Security: each user can only see/edit their own trips
alter table public.trips enable row level security;

drop policy if exists "Users can read own trips"   on public.trips;
drop policy if exists "Users can insert own trips"  on public.trips;
drop policy if exists "Users can update own trips"  on public.trips;
drop policy if exists "Users can delete own trips"  on public.trips;

create policy "Users can read own trips"
  on public.trips for select
  using (auth.uid() = user_id);

create policy "Users can insert own trips"
  on public.trips for insert
  with check (auth.uid() = user_id);

create policy "Users can update own trips"
  on public.trips for update
  using (auth.uid() = user_id);

create policy "Users can delete own trips"
  on public.trips for delete
  using (auth.uid() = user_id);


-- ── Community contributions ──────────────────────────────────────────
create table if not exists public.contributions (
  id          uuid        primary key default gen_random_uuid(),
  leg_key     text        not null,   -- e.g. "istanbul-ankara-train"
  user_id     uuid        references public.profiles(id) on delete set null,
  kind        text        not null,   -- price | schedule | border | tip | confirmed | warning
  text        text        not null,
  source      text        default '',
  votes       int         not null default 0,
  created_at  timestamptz not null default now()
);

create index if not exists contrib_leg_key_idx on public.contributions(leg_key);

-- Migration: re-point user_id FK → public.profiles so PostgREST can auto-join
-- profiles(display_name, email) in contributions queries. Safe to re-run.
alter table public.contributions
  drop constraint if exists contributions_user_id_fkey;
alter table public.contributions
  add constraint contributions_user_id_fkey
    foreign key (user_id) references public.profiles(id) on delete set null;

alter table public.contributions enable row level security;

drop policy if exists "Anyone can read contributions"               on public.contributions;
drop policy if exists "Authenticated users can insert contributions" on public.contributions;
drop policy if exists "Users can update own contributions"           on public.contributions;

create policy "Anyone can read contributions"
  on public.contributions for select
  using (true);

create policy "Authenticated users can insert contributions"
  on public.contributions for insert
  with check (auth.uid() = user_id);

create policy "Users can update own contributions"
  on public.contributions for update
  using (auth.uid() = user_id);


-- ── Profiles (auto-created on sign-up via trigger) ───────────────────
create table if not exists public.profiles (
  id          uuid        primary key references auth.users(id) on delete cascade,
  email       text,
  display_name text       default '',
  avatar_url  text        default '',
  location    text        default '',
  karma       int         not null default 0,
  created_at  timestamptz not null default now()
);

-- Add location column if upgrading from older schema
alter table public.profiles add column if not exists location text default '';

-- Add preferred_currency column if upgrading from older schema
alter table public.profiles add column if not exists preferred_currency text not null default 'USD';

-- Admin flag (used for gating admin.html and admin-only RLS writes)
alter table public.profiles add column if not exists is_admin boolean not null default false;

-- Seed known admin accounts (idempotent; matches on email).
update public.profiles
  set is_admin = true
  where email in ('srohan8@gmail.com');

alter table public.profiles enable row level security;

drop policy if exists "Anyone can read profiles"      on public.profiles;
drop policy if exists "Users can update own profile"  on public.profiles;

create policy "Anyone can read profiles"
  on public.profiles for select using (true);

create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

-- Trigger: create a profile row whenever a user signs up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- ── Voting & Confirmation tables ─────────────────────────────────────

-- Add confirmed_count to contributions (idempotent)
alter table public.contributions add column if not exists confirmed_count int not null default 0;

-- contribution_votes: tracks who voted on which contribution (prevents double-voting)
create table if not exists public.contribution_votes (
  contribution_id uuid references public.contributions(id) on delete cascade,
  user_id         uuid references auth.users(id) on delete cascade,
  primary key (contribution_id, user_id)
);

alter table public.contribution_votes enable row level security;

drop policy if exists "Anyone can read contribution_votes"                on public.contribution_votes;
drop policy if exists "Authenticated users can insert own vote"           on public.contribution_votes;
drop policy if exists "Users can delete own vote"                         on public.contribution_votes;

create policy "Anyone can read contribution_votes"
  on public.contribution_votes for select
  using (true);

create policy "Authenticated users can insert own vote"
  on public.contribution_votes for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own vote"
  on public.contribution_votes for delete
  using (auth.uid() = user_id);


-- contribution_confirms: tracks who confirmed a contribution note
create table if not exists public.contribution_confirms (
  contribution_id uuid references public.contributions(id) on delete cascade,
  user_id         uuid references auth.users(id) on delete cascade,
  primary key (contribution_id, user_id)
);

alter table public.contribution_confirms enable row level security;

drop policy if exists "Anyone can read contribution_confirms"             on public.contribution_confirms;
drop policy if exists "Authenticated users can insert own confirm"        on public.contribution_confirms;
drop policy if exists "Users can delete own confirm"                      on public.contribution_confirms;

create policy "Anyone can read contribution_confirms"
  on public.contribution_confirms for select
  using (true);

create policy "Authenticated users can insert own confirm"
  on public.contribution_confirms for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own confirm"
  on public.contribution_confirms for delete
  using (auth.uid() = user_id);


-- ── Karma trigger functions ───────────────────────────────────────────

-- +15 karma when a user posts a new contribution
create or replace function public.handle_new_contribution()
returns trigger language plpgsql security definer as $$
begin
  if new.user_id is not null then
    update public.profiles
    set karma = karma + 15
    where id = new.user_id;
  end if;
  return new;
end;
$$;

drop trigger if exists on_new_contribution on public.contributions;
create trigger on_new_contribution
  after insert on public.contributions
  for each row execute procedure public.handle_new_contribution();


-- +2 karma to the contribution author when someone votes on their contribution
create or replace function public.handle_new_vote()
returns trigger language plpgsql security definer as $$
declare
  v_author_id uuid;
begin
  select user_id into v_author_id
  from public.contributions
  where id = new.contribution_id;

  if v_author_id is not null then
    update public.profiles
    set karma = karma + 2
    where id = v_author_id;
  end if;
  return new;
end;
$$;

drop trigger if exists on_new_contribution_vote on public.contribution_votes;
create trigger on_new_contribution_vote
  after insert on public.contribution_votes
  for each row execute procedure public.handle_new_vote();


-- +25 karma to the contribution author when someone confirms their contribution
create or replace function public.handle_new_confirm()
returns trigger language plpgsql security definer as $$
declare
  v_author_id uuid;
begin
  select user_id into v_author_id
  from public.contributions
  where id = new.contribution_id;

  if v_author_id is not null then
    update public.profiles
    set karma = karma + 25
    where id = v_author_id;
  end if;
  return new;
end;
$$;

drop trigger if exists on_new_contribution_confirm on public.contribution_confirms;
create trigger on_new_contribution_confirm
  after insert on public.contribution_confirms
  for each row execute procedure public.handle_new_confirm();


-- ── Helper RPC: atomically increment confirmed_count ─────────────────
create or replace function public.increment_confirmed(contrib_id uuid)
returns void language plpgsql security definer as $$
begin
  update public.contributions
  set confirmed_count = confirmed_count + 1
  where id = contrib_id;
end;
$$;


-- ── Admin settings (key-value, admin-writable) ───────────────────────
-- Read-any (needed so the app can read toggles like maintenance_mode
-- without auth); writes gated to admins only.
create table if not exists public.admin_settings (
  key         text        primary key,
  value       jsonb,
  updated_at  timestamptz not null default now()
);

alter table public.admin_settings enable row level security;

drop policy if exists "Anyone can read admin_settings"  on public.admin_settings;
drop policy if exists "Admins can insert admin_settings" on public.admin_settings;
drop policy if exists "Admins can update admin_settings" on public.admin_settings;
drop policy if exists "Admins can delete admin_settings" on public.admin_settings;

create policy "Anyone can read admin_settings"
  on public.admin_settings for select using (true);

create policy "Admins can insert admin_settings"
  on public.admin_settings for insert
  with check (exists (
    select 1 from public.profiles where id = auth.uid() and is_admin
  ));

create policy "Admins can update admin_settings"
  on public.admin_settings for update
  using (exists (
    select 1 from public.profiles where id = auth.uid() and is_admin
  ));

create policy "Admins can delete admin_settings"
  on public.admin_settings for delete
  using (exists (
    select 1 from public.profiles where id = auth.uid() and is_admin
  ));


-- ── Conflict zones (travel advisories) ───────────────────────────────
-- Source of truth: FCDO + Government of Canada (refreshed daily by
-- proxy/refresh-advisories.js). State Dept / AU / DE / FR / JP are
-- stored as per-country deep-link URLs for cross-checking only.
create table if not exists public.conflict_zones (
  country_code       text        primary key,        -- ISO-2 uppercase
  country_name       text        not null,
  level              text        not null,           -- war | conflict | tension | advisory
  summary            text        default '',
  fcdo_url           text,
  canada_url         text,
  state_dept_url     text,
  smartraveller_url  text,                           -- Australia
  germany_url        text,
  france_url         text,
  japan_url          text,
  source_updated_at  timestamptz,                    -- latest FCDO/Canada page timestamp
  reviewed_at        timestamptz not null default now(),
  created_at         timestamptz not null default now()
);

alter table public.conflict_zones enable row level security;

drop policy if exists "Anyone can read conflict_zones" on public.conflict_zones;
create policy "Anyone can read conflict_zones"
  on public.conflict_zones for select
  using (true);
-- Writes: service-role only (the refresh cron uses the service key).


-- ── Seed: high-risk countries referenced by the planner ──────────────
-- Refreshed daily; hand-seeded baseline so the app is usable before
-- the first cron run and for countries the refresh job may miss.
insert into public.conflict_zones
  (country_code, country_name, level, summary, fcdo_url, canada_url, state_dept_url, smartraveller_url, germany_url, france_url, japan_url)
values
  ('AF','Afghanistan','war','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/afghanistan',
    'https://travel.gc.ca/destinations/afghanistan',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Afghanistan.html',
    'https://www.smartraveller.gov.au/destinations/asia/afghanistan',
    'https://www.auswaertiges-amt.de/de/service/laender/afghanistan-node/afghanistansicherheit/204676',
    'https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays-destination/afghanistan/',
    'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_004.html'),
  ('MM','Myanmar','war','FCDO advises against all travel to most of the country.',
    'https://www.gov.uk/foreign-travel-advice/myanmar-burma',
    'https://travel.gc.ca/destinations/myanmar',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Burma.html',
    'https://www.smartraveller.gov.au/destinations/asia/myanmar',
    'https://www.auswaertiges-amt.de/de/service/laender/myanmar-node/myanmarsicherheit/208384',
    'https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays-destination/birmanie/',
    'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_022.html'),
  ('SD','Sudan','war','Active civil conflict. FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/sudan',
    'https://travel.gc.ca/destinations/sudan',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Sudan.html',
    'https://www.smartraveller.gov.au/destinations/africa/sudan',
    'https://www.auswaertiges-amt.de/de/service/laender/sudan-node/sudansicherheit/210826',
    'https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays-destination/soudan/',
    null),
  ('SS','South Sudan','war','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/south-sudan',
    'https://travel.gc.ca/destinations/south-sudan',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/SouthSudan.html',
    'https://www.smartraveller.gov.au/destinations/africa/south-sudan',
    null, null, null),
  ('SY','Syria','war','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/syria',
    'https://travel.gc.ca/destinations/syria',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Syria.html',
    'https://www.smartraveller.gov.au/destinations/middle-east/syria',
    'https://www.auswaertiges-amt.de/de/service/laender/syrien-node/syriensicherheit/211046',
    'https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays-destination/syrie/',
    null),
  ('YE','Yemen','war','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/yemen',
    'https://travel.gc.ca/destinations/yemen',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Yemen.html',
    'https://www.smartraveller.gov.au/destinations/middle-east/yemen',
    null, null, null),
  ('SO','Somalia','war','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/somalia',
    'https://travel.gc.ca/destinations/somalia',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Somalia.html',
    'https://www.smartraveller.gov.au/destinations/africa/somalia',
    null, null, null),
  ('LY','Libya','war','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/libya',
    'https://travel.gc.ca/destinations/libya',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Libya.html',
    'https://www.smartraveller.gov.au/destinations/africa/libya',
    null, null, null),
  ('KP','North Korea','war','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/north-korea',
    'https://travel.gc.ca/destinations/korea-north',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/NorthKorea.html',
    'https://www.smartraveller.gov.au/destinations/asia/north-korea',
    null, null, null),
  ('UA','Ukraine','war','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/ukraine',
    'https://travel.gc.ca/destinations/ukraine',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Ukraine.html',
    'https://www.smartraveller.gov.au/destinations/europe/ukraine',
    'https://www.auswaertiges-amt.de/de/service/laender/ukraine-node/ukrainesicherheit/201946',
    'https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays-destination/ukraine/',
    null),
  ('RU','Russia','conflict','FCDO advises against all but essential travel.',
    'https://www.gov.uk/foreign-travel-advice/russia',
    'https://travel.gc.ca/destinations/russia',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/RussianFederation.html',
    'https://www.smartraveller.gov.au/destinations/europe/russia',
    'https://www.auswaertiges-amt.de/de/service/laender/russischefoederation-node/russischefoederationsicherheit/201536',
    'https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays-destination/russie/',
    null),
  ('BY','Belarus','conflict','FCDO advises against all but essential travel.',
    'https://www.gov.uk/foreign-travel-advice/belarus',
    'https://travel.gc.ca/destinations/belarus',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Belarus.html',
    'https://www.smartraveller.gov.au/destinations/europe/belarus',
    null, null, null),
  ('IR','Iran','conflict','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/iran',
    'https://travel.gc.ca/destinations/iran',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Iran.html',
    'https://www.smartraveller.gov.au/destinations/middle-east/iran',
    'https://www.auswaertiges-amt.de/de/service/laender/iran-node/iransicherheit/203400',
    'https://www.diplomatie.gouv.fr/fr/conseils-aux-voyageurs/conseils-par-pays-destination/iran/',
    null),
  ('IQ','Iraq','conflict','FCDO advises against all but essential travel.',
    'https://www.gov.uk/foreign-travel-advice/iraq',
    'https://travel.gc.ca/destinations/iraq',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Iraq.html',
    'https://www.smartraveller.gov.au/destinations/middle-east/iraq',
    null, null, null),
  ('HT','Haiti','conflict','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/haiti',
    'https://travel.gc.ca/destinations/haiti',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Haiti.html',
    'https://www.smartraveller.gov.au/destinations/americas/haiti',
    null, null, null),
  ('VE','Venezuela','conflict','FCDO advises against all but essential travel.',
    'https://www.gov.uk/foreign-travel-advice/venezuela',
    'https://travel.gc.ca/destinations/venezuela',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Venezuela.html',
    'https://www.smartraveller.gov.au/destinations/americas/venezuela',
    null, null, null),
  ('ML','Mali','conflict','FCDO advises against all travel.',
    'https://www.gov.uk/foreign-travel-advice/mali',
    'https://travel.gc.ca/destinations/mali',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Mali.html',
    'https://www.smartraveller.gov.au/destinations/africa/mali',
    null, null, null),
  ('PK','Pakistan','tension','FCDO advises against all travel to parts of the country.',
    'https://www.gov.uk/foreign-travel-advice/pakistan',
    'https://travel.gc.ca/destinations/pakistan',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Pakistan.html',
    'https://www.smartraveller.gov.au/destinations/asia/pakistan',
    null, null, null),
  ('LB','Lebanon','tension','FCDO advises against all but essential travel.',
    'https://www.gov.uk/foreign-travel-advice/lebanon',
    'https://travel.gc.ca/destinations/lebanon',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Lebanon.html',
    'https://www.smartraveller.gov.au/destinations/middle-east/lebanon',
    null, null, null),
  ('IN','India','advisory','Exercise normal precautions; elevated risk in some border areas.',
    'https://www.gov.uk/foreign-travel-advice/india',
    'https://travel.gc.ca/destinations/india',
    'https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/India.html',
    'https://www.smartraveller.gov.au/destinations/asia/india',
    null, null, null)
on conflict (country_code) do update set
  country_name      = excluded.country_name,
  level             = excluded.level,
  summary           = excluded.summary,
  fcdo_url          = excluded.fcdo_url,
  canada_url        = excluded.canada_url,
  state_dept_url    = excluded.state_dept_url,
  smartraveller_url = excluded.smartraveller_url,
  germany_url       = coalesce(excluded.germany_url, public.conflict_zones.germany_url),
  france_url        = coalesce(excluded.france_url,  public.conflict_zones.france_url),
  japan_url         = coalesce(excluded.japan_url,   public.conflict_zones.japan_url),
  reviewed_at       = now();
