-- ── Booking sites (country-priority matching + one-time bulk seeding) ──
-- See plan: docs/agents (or the vivid-doodling-simon implementation plan)
-- for full context. Three tables:
--   1. booking_sites          — the live, admin-curated site list (replaces
--      the previous localStorage-only DEFAULT_SITES/slw_all_sites setup).
--   2. seeded_countries       — tracks which country+category combos have
--      already had a Brave sweep attempted (bulk or reactive), so the
--      reactive trigger (§10) never double-fires.
--   3. booking_sites_pending  — raw Brave results awaiting admin review,
--      written both by the admin-triggered bulk sweep and by the reactive
--      first-time-country trigger (which runs from a regular user's
--      session, hence the service-key-only write path via the proxy).

create table if not exists public.booking_sites (
  id            text primary key,
  name          text not null,
  category      text not null,           -- 'buses' | 'trains' | 'ferries' | 'ships' | 'accommodation' | 'info'
  url_template  text not null,
  aff_id        text default '',
  regions       text[] not null default '{}',
  countries     text[] not null default '{}',
  enabled       boolean not null default true,
  builtin       boolean not null default false,
  source        text not null default 'admin',  -- 'admin' | 'bulk_seed'
  admin_edited  boolean not null default true,   -- false only for freshly-promoted
                                                   -- bulk_seed/reactive rows; "NEW" badge
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

alter table public.booking_sites enable row level security;

drop policy if exists "Anyone can read booking_sites" on public.booking_sites;
create policy "Anyone can read booking_sites"
  on public.booking_sites for select using (true);

drop policy if exists "Admins can insert booking_sites" on public.booking_sites;
create policy "Admins can insert booking_sites"
  on public.booking_sites for insert
  with check (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

drop policy if exists "Admins can update booking_sites" on public.booking_sites;
create policy "Admins can update booking_sites"
  on public.booking_sites for update
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

drop policy if exists "Admins can delete booking_sites" on public.booking_sites;
create policy "Admins can delete booking_sites"
  on public.booking_sites for delete
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin));


-- ── Seeded countries (§10) ────────────────────────────────────────────
-- Records "we've already attempted a Brave sweep for this country+category,"
-- independent of whether anything from it was ultimately approved. The
-- primary key doubles as the race guard for the reactive trigger — insert
-- before calling Brave, and only proceed if the insert actually landed.
create table if not exists public.seeded_countries (
  country_code  text not null,
  category      text not null,
  seeded_at     timestamptz not null default now(),
  primary key (country_code, category)
);

alter table public.seeded_countries enable row level security;

drop policy if exists "Anyone can read seeded_countries" on public.seeded_countries;
create policy "Anyone can read seeded_countries"
  on public.seeded_countries for select using (true);

-- Writes: any authenticated-or-anon browser session can race to claim a
-- country+category (that's the point of the reactive trigger — it fires
-- from a regular traveler's session, not an admin's). The primary key
-- itself is the guard against double-processing, not RLS.
drop policy if exists "Anyone can insert seeded_countries" on public.seeded_countries;
create policy "Anyone can insert seeded_countries"
  on public.seeded_countries for insert with check (true);


-- ── Pending review queue (§6 bulk sweep + §10 reactive trigger) ───────
-- Raw Brave results awaiting admin review before promotion into
-- booking_sites. Both the admin-triggered bulk sweep and the reactive
-- first-time-country trigger write here — the reactive path runs from a
-- non-admin browser session, so it can't satisfy is_admin-gated insert RLS
-- directly; that path goes through proxy/server.js's
-- POST /api/queue-seed-result using SUPABASE_SERVICE_KEY instead.
create table if not exists public.booking_sites_pending (
  id              bigint generated by default as identity primary key,
  country_code    text not null,
  category        text not null,
  title           text default '',
  url             text not null,
  description     text default '',
  trigger_source  text not null default 'bulk_seed',  -- 'bulk_seed' | 'reactive_new_country'
  reviewed        boolean not null default false,
  created_at      timestamptz not null default now()
);

alter table public.booking_sites_pending enable row level security;

drop policy if exists "Admins can read booking_sites_pending" on public.booking_sites_pending;
create policy "Admins can read booking_sites_pending"
  on public.booking_sites_pending for select
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

drop policy if exists "Admins can insert booking_sites_pending" on public.booking_sites_pending;
create policy "Admins can insert booking_sites_pending"
  on public.booking_sites_pending for insert
  with check (exists (select 1 from public.profiles where id = auth.uid() and is_admin));
-- Note: the reactive-trigger insert path (non-admin sessions) bypasses this
-- policy entirely via the service-role key in proxy/server.js — it never
-- goes through the browser's anon/authenticated Supabase client.

drop policy if exists "Admins can update booking_sites_pending" on public.booking_sites_pending;
create policy "Admins can update booking_sites_pending"
  on public.booking_sites_pending for update
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

drop policy if exists "Admins can delete booking_sites_pending" on public.booking_sites_pending;
create policy "Admins can delete booking_sites_pending"
  on public.booking_sites_pending for delete
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin));


-- ── Seed data: today's DEFAULT_SITES (app/index.html), so a fresh project
-- starts with the current built-in list. countries[] left empty for all —
-- populated later by the bulk-seed sweep (§6) and reactive trigger (§10).
insert into public.booking_sites (id, name, category, url_template, aff_id, regions, countries, enabled, builtin, source, admin_edited) values
  ('_bi_busbud',   'Busbud',               'buses',  'https://www.busbud.com/en/bus-{origin}-{dest}',                                             '', array['North America','Latin America','Europe','Middle East','Southeast Asia'], '{}', true, true, 'admin', true),
  ('_bi_bookaway', 'Bookaway',             'buses',  'https://www.bookaway.com/search?srcName={origin}&dstName={dest}',                           '', array['Southeast Asia','Central Asia','South Asia','Middle East','East Asia','Latin America','Africa'], '{}', true, true, 'admin', true),
  ('_bi_12go',     '12Go',                 'buses',  'https://12go.asia/en/travel/{origin}/{dest}',                                                '', array['Southeast Asia','Central Asia','South Asia','East Asia'], '{}', true, true, 'admin', true),
  ('_bi_flixbus',  'FlixBus',              'buses',  'https://shop.flixbus.com/search?departureCity={origin}&arrivalCity={dest}',                 '', array['Europe','North America'], '{}', true, true, 'admin', true),
  ('_bi_getbybus', 'GetByBus',             'buses',  'https://getbybus.com/en/bus/{origin}/{dest}',                                                '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_omio_b',   'Omio',                 'buses',  'https://www.omio.com/app/search-results?origin={origin}&destination={dest}',                '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_omio_t',   'Omio',                 'trains', 'https://www.omio.com/app/search-results?origin={origin}&destination={dest}&transportType=train', '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_raileu',   'Rail Europe',          'trains', 'https://www.raileurope.com/en/search#from={origin}&to={dest}',                              '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_trainline','Trainline',            'trains', 'https://www.thetrainline.com/search/{origin}/{dest}',                                       '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_eurostar', 'Eurostar',             'trains', 'https://www.eurostar.com/uk-en/search#origin={origin}&destination={dest}',                  '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_sncf',     'SNCF Connect',         'trains', 'https://www.sncf-connect.com/en-en/app/search/result?originCode={origin}&destinationCode={dest}', '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_db',       'Deutsche Bahn',        'trains', 'https://www.bahn.de/buchung/fahrplan/suche#sts=true&so={origin}&zo={dest}',                 '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_obb',      'OBB',                  'trains', 'https://fahrplan.oebb.at/bin/query.exe/en?S={origin}&Z={dest}',                             '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_mav',      'MAV',                  'trains', 'https://jegy.mav.hu/search?from={origin}&to={dest}',                                        '', array['Europe'], '{}', true, true, 'admin', true),
  ('_bi_obilet',   'Obilet',               'buses',  'https://www.obilet.com/seferler/{origin}-{dest}',                                           '', array['Middle East'], '{}', true, true, 'admin', true),
  ('_bi_metrotur', 'Metro Turizm',         'buses',  'https://www.metroturizm.com.tr/en/route/{origin}/{dest}',                                   '', array['Middle East'], '{}', true, true, 'admin', true),
  ('_bi_tcdd',     'TCDD',                 'trains', 'https://bilet.tcdd.gov.tr/home?sehirden={origin}&sehire={dest}',                            '', array['Middle East'], '{}', true, true, 'admin', true),
  ('_bi_raja',     'RAJA Trains',          'trains', 'https://www.raja.ir/fa/trains?origin={origin}&destination={dest}',                          '', array['Middle East'], '{}', true, true, 'admin', true),
  ('_bi_1stquest', '1stQuest',             'buses',  'https://www.1stquest.ir/bus/{origin}/{dest}',                                                '', array['Middle East'], '{}', true, true, 'admin', true),
  ('_bi_redbus',   'RedBus',               'buses',  'https://www.redbus.in/bus-tickets/{origin}-to-{dest}',                                      '', array['South Asia'], '{}', true, true, 'admin', true),
  ('_bi_cleartrip','Cleartrip',            'buses',  'https://www.cleartrip.com/bus/{origin}-to-{dest}/',                                         '', array['South Asia'], '{}', true, true, 'admin', true),
  ('_bi_irctc',    'IRCTC',                'trains', 'https://www.irctc.co.in/nget/train-search?fromStation={origin}&toStation={dest}',           '', array['South Asia'], '{}', true, true, 'admin', true),
  ('_bi_pakrail',  'Pakistan Railways',    'trains', 'https://www.pakrail.gov.pk/train_schedule?from={origin}&to={dest}',                         '', array['South Asia'], '{}', true, true, 'admin', true),
  ('_bi_baolau',   'Baolau',               'buses',  'https://www.baolau.com/search/result?from={origin}&to={dest}',                              '', array['Southeast Asia'], '{}', true, true, 'admin', true),
  ('_bi_easybook', 'Easybook',             'buses',  'https://www.easybook.com/en-sg/bus/{origin}/{dest}',                                        '', array['Southeast Asia'], '{}', true, true, 'admin', true),
  ('_bi_recorrido','Recorrido',            'buses',  'https://www.recorrido.cl/es/bus/{origin}/{dest}',                                           '', array['Latin America'], '{}', true, true, 'admin', true),
  ('_bi_blablacar','BlaBlaCar',            'buses',  'https://www.blablacar.com/search?source={origin}&destination={dest}',                       '', array['Europe','Latin America','South Asia','Middle East'], '{}', true, true, 'admin', true),
  ('_bi_dferries', 'Direct Ferries',       'ferries','https://www.directferries.com/ferry_{origin}_{dest}.htm',                                   '', array['Europe','Southeast Asia','Oceania','Middle East'], '{}', true, true, 'admin', true),
  ('_bi_rome2rio',     'Rome2rio',           'info', 'https://www.rome2rio.com/s/{origin}/{dest}',      '', '{}', '{}', true, true, 'admin', true),
  ('_bi_seat61',       'The Man in Seat 61', 'info', 'https://www.seat61.com/?s={dest}',                 '', array['Europe','Middle East','Central Asia','South Asia','East Asia'], '{}', true, true, 'admin', true),
  ('_bi_caravanistan', 'Caravanistan',       'info', 'https://caravanistan.com/?s={origin}+to+{dest}',   '', array['Central Asia','Middle East'], '{}', true, true, 'admin', true),
  ('_bi_booking',  'Booking.com',          'accommodation', 'https://www.booking.com/search.html?ss={origin}',                                    '', '{}', '{}', true, true, 'admin', true),
  ('_bi_hostelw',  'Hostelworld',          'accommodation', 'https://www.hostelworld.com/findabed.php/ChosenCity.{origin}',                       '', '{}', '{}', true, true, 'admin', true),
  ('_bi_agoda',    'Agoda',                'accommodation', 'https://www.agoda.com/search?city={origin}',                                         '', array['Southeast Asia','East Asia','South Asia','Middle East'], '{}', true, true, 'admin', true),
  ('_bi_airbnb',   'Airbnb',               'accommodation', 'https://www.airbnb.com/s/{origin}/homes',                                            '', '{}', '{}', true, true, 'admin', true)
on conflict (id) do nothing;
